<a href="https://colab.research.google.com/github/Dhritika02/Dhritika_ML_Internship_2026/blob/master/week2Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, confusion_matrix

In [3]:
from google.colab import files

uploaded = files.upload()

Saving Dataset 2Assignment1.csv to Dataset 2Assignment1 (1).csv

Q1-Load the dataset and display the first five records.

In [5]:
df = pd.read_csv("Dataset 2Assignment1.csv")
df.head()

,UserID,Age,Gender,SubscriptionType,WatchHoursPerWeek,DevicesUsed,FavoriteGenre,AdClicks,MonthlySpend,SubscriptionRenewed
0,1001,22,Female,Basic,23,5,Comedy,13,353,No
1,1002,55,Male,Basic,9,4,Drama,14,317,Yes
2,1003,49,Male,Basic,8,3,Comedy,16,309,No
3,1004,39,Female,Premium,19,5,Drama,45,833,Yes
4,1005,38,Female,Premium,23,5,Sci-Fi,24,804,Yes

Q2.
Determine the number of rows and columns in the dataset.

In [6]:
print(df.shape)

(750, 10)

Q3.
Display all column names.

In [7]:
print(df.columns)

Index(['UserID', 'Age', 'Gender', 'SubscriptionType', 'WatchHoursPerWeek',
       'DevicesUsed', 'FavoriteGenre', 'AdClicks', 'MonthlySpend',
       'SubscriptionRenewed'],
      dtype='object')

Q4.
Identify numerical and categorical features.

In [10]:
print(df.sum())

UserID                                                           1031625
Age                                                                31368
Gender                 FemaleMaleMaleFemaleFemaleMaleFemaleMaleMaleFe...
SubscriptionType       BasicBasicBasicPremiumPremiumBasicBasicVIPBasi...
WatchHoursPerWeek                                                  10677
DevicesUsed                                                         2260
FavoriteGenre          ComedyDramaComedyDramaSci-FiComedyComedyHorror...
AdClicks                                                           17379
MonthlySpend                                                      517429
SubscriptionRenewed    NoYesNoYesYesYesNoYesNoNoNoYesYesNoYesNoNoNoNo...
dtype: object

Q5.
Check whether the dataset contains missing values.

In [11]:
print(df.isnull())

     UserID    Age  Gender  SubscriptionType  WatchHoursPerWeek  DevicesUsed  \
0     False  False   False             False              False        False
1     False  False   False             False              False        False
2     False  False   False             False              False        False
3     False  False   False             False              False        False
4     False  False   False             False              False        False
..      ...    ...     ...               ...                ...          ...
745   False  False   False             False              False        False
746   False  False   False             False              False        False
747   False  False   False             False              False        False
748   False  False   False             False              False        False
749   False  False   False             False              False        False

     FavoriteGenre  AdClicks  MonthlySpend  SubscriptionRenewed
0            False     False         False                False
1            False     False         False                False
2            False     False         False                False
3            False     False         False                False
4            False     False         False                False
..             ...       ...           ...                  ...
745          False     False         False                False
746          False     False         False                False
747          False     False         False                False
748          False     False         False                False
749          False     False         False                False

[750 rows x 10 columns]

Q6.
Calculate the average age of users.

In [13]:
print(df["Age"].mean())

41.824

Q7.
Determine the average watch hours per week

In [12]:
print(df["WatchHoursPerWeek"].mean())

14.236

Q8.
Find the average monthly spending of users.

In [15]:
print(df["MonthlySpend"].mean())

689.9053333333334

Q9.
Count the number of users in each subscription category.

In [14]:
print(df["SubscriptionType"].value_counts())

SubscriptionType
Basic      342
Premium    279
VIP        129
Name: count, dtype: int64

Q10.
Determine the percentage of users who renewed their subscriptions.

In [17]:
renewal = (df["SubscriptionRenewed"] == "Yes").mean() * 100
print(renewal)

46.266666666666666

Part C: Data Preparation

Q11.
Convert categorical features into numerical form.

Q12.
Define the feature set (X) and target variable (y) for subscription renewal prediction.

Q13.
Split the dataset into training and testing sets.

In [18]:
encode = LabelEncoder()

for col in df.select_dtypes(include='object').columns:
    df[col] = encode.fit_transform(df[col])

df.head()

,UserID,Age,Gender,SubscriptionType,WatchHoursPerWeek,DevicesUsed,FavoriteGenre,AdClicks,MonthlySpend,SubscriptionRenewed
0,1001,22,0,0,23,5,1,13,353,0
1,1002,55,1,0,9,4,2,14,317,1
2,1003,49,1,0,8,3,1,16,309,0
3,1004,39,0,1,19,5,2,45,833,1
4,1005,38,0,1,23,5,5,24,804,1

Part D: Decision Tree Classification

Q14.
Train a Decision Tree model to predict whether a user will renew their subscription.

Q15.
Evaluate the model using accuracy.

Q16.
Generate and interpret the confusion matrix.

In [19]:
X = df.drop("SubscriptionRenewed", axis=1)
y = df["SubscriptionRenewed"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
pred = dt.predict(X_test)
print("Accuracy:", accuracy_score(y_test, pred))
print(confusion_matrix(y_test, pred))

Accuracy: 0.5866666666666667
[[51 31]
 [31 37]]

Part E: K-Nearest Neighbors (KNN)

Q17.
Train a KNN classifier with K = 5.

Q18.
Compare the accuracy of KNN with the Decision Tree model

In [20]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
pred_knn = knn.predict(X_test)
print(accuracy_score(y_test, pred_knn))

0.6

Part F: Linear Regression

Q19.
Train a Linear Regression model to predict monthly spending.

Q20.
Predict the monthly spending for a new user and interpret the result.

In [24]:
X_reg = df.drop("MonthlySpend", axis=1)
y_reg = df["MonthlySpend"]
X_train, X_test, y_train, y_test = train_test_split(X_reg, y_reg,test_size=0.2,random_state=42)
lr = LinearRegression()
lr.fit(X_train, y_train)
new_user = pd.DataFrame({
    'UserID': [1751],
    'Age': [25],
    'Gender': [1],
    'SubscriptionType': [2],
    'WatchHoursPerWeek': [20],
    'DevicesUsed': [2],
    'FavoriteGenre': [1],
    'AdClicks': [5],
    'SubscriptionRenewed': [1]})
ps = lr.predict(new_user)
print("Predicted Monthly Spending", round(ps[0], 2))

Predicted Monthly Spending 1334.79